//! Parser implementation. Generated by CongoCC Parser Generator. Do not edit.

use crate::error::{ParseError, ParseResult};
use crate::tokens::{Token, TokenType};
use crate::lexer::Lexer;
use crate::arena::{Arena, AstNode, NodeId, TokenId};
use crate::arena::{
    JmsSelectorNode,
    OrExpressionNode,
    AndExpressionNode,
    EqualityExpressionNode,
    ComparisonExpressionNode,
    AddExpressionNode,
    MultExprNode,
    UnaryExprNode,
    PrimaryExprNode,
    LiteralNode,
    StringLitteralNode,
    VariableNode
};

/// The parser for SqlExprParser
pub struct Parser {
    /// The lexer providing tokens
    lexer: Lexer,
    /// Current token being examined
    current_token: Token,
    /// Lookahead tokens
    lookahead: Vec<Token>,
    /// Arena owning all AST nodes and tokens
    arena: Arena,
    /// ID of the most recently allocated token
    current_token_id: Option<TokenId>,
    /// Original input string
    input: String,
}

impl Parser {
    /// Create a new parser for the given input
    pub fn new(input: String) -> ParseResult<Self> {
        let mut lexer = Lexer::new(input.clone());
        let current_token = lexer.next_token()?;

        Ok(Parser {
            lexer,
            current_token,
            lookahead: Vec::new(),
            arena: Arena::new(),
            current_token_id: None,
            input,
        })
    }

    /// Get a reference to the arena containing all AST nodes
    pub fn arena(&self) -> &Arena {
        &self.arena
    }

    /// Get a mutable reference to the arena
    pub fn arena_mut(&mut self) -> &mut Arena {
        &mut self.arena
    }

    /// Get the original input string
    pub fn input(&self) -> &str {
        &self.input
    }

    /// Parse the input and return the root node ID
    pub fn parse(&mut self) -> ParseResult<NodeId> {
        self.parse_jms_selector()
    }

    /// Parse: JmsSelector
    fn parse_jms_selector(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = JmsSelectorNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::JmsSelector(node));
        Ok(node_id)
    }

    /// Parse: orExpression
    fn parse_or_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = OrExpressionNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::OrExpression(node));
        Ok(node_id)
    }

    /// Parse: andExpression
    fn parse_and_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = AndExpressionNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::AndExpression(node));
        Ok(node_id)
    }

    /// Parse: equalityExpression
    fn parse_equality_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = EqualityExpressionNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::EqualityExpression(node));
        Ok(node_id)
    }

    /// Parse: comparisonExpression
    fn parse_comparison_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = ComparisonExpressionNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::ComparisonExpression(node));
        Ok(node_id)
    }

    /// Parse: addExpression
    fn parse_add_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = AddExpressionNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::AddExpression(node));
        Ok(node_id)
    }

    /// Parse: multExpr
    fn parse_mult_expr(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = MultExprNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::MultExpr(node));
        Ok(node_id)
    }

    /// Parse: unaryExpr
    fn parse_unary_expr(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = UnaryExprNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::UnaryExpr(node));
        Ok(node_id)
    }

    /// Parse: primaryExpr
    fn parse_primary_expr(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = PrimaryExprNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::PrimaryExpr(node));
        Ok(node_id)
    }

    /// Parse: literal
    fn parse_literal(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = LiteralNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::Literal(node));
        Ok(node_id)
    }

    /// Parse: stringLitteral
    fn parse_string_litteral(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = StringLitteralNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::StringLitteral(node));
        Ok(node_id)
    }

    /// Parse: variable
    fn parse_variable(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let children: Vec<NodeId> = Vec::new();
        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = VariableNode::new(begin_token, end_token);
        node.children = children;
        let node_id = self.arena.alloc_node(AstNode::Variable(node));
        Ok(node_id)
    }

    // ========== Helper Methods ==========

    /// Set the parent of a node
    fn set_parent(&mut self, child_id: NodeId, parent_id: NodeId) {
        match self.arena.get_node_mut(child_id) {
            AstNode::JmsSelector(node) => node.parent = Some(parent_id),
            AstNode::OrExpression(node) => node.parent = Some(parent_id),
            AstNode::AndExpression(node) => node.parent = Some(parent_id),
            AstNode::EqualityExpression(node) => node.parent = Some(parent_id),
            AstNode::ComparisonExpression(node) => node.parent = Some(parent_id),
            AstNode::AddExpression(node) => node.parent = Some(parent_id),
            AstNode::MultExpr(node) => node.parent = Some(parent_id),
            AstNode::UnaryExpr(node) => node.parent = Some(parent_id),
            AstNode::PrimaryExpr(node) => node.parent = Some(parent_id),
            AstNode::Literal(node) => node.parent = Some(parent_id),
            AstNode::StringLitteral(node) => node.parent = Some(parent_id),
            AstNode::Variable(node) => node.parent = Some(parent_id),
        }
    }

    /// Check if the current token matches any of the given types
    #[allow(dead_code)]
    fn current_token_matches(&self, types: &[TokenType]) -> bool {
        types.contains(&self.current_token.token_type)
    }

    /// Consume the current token and advance to the next one
    fn consume_token(&mut self) -> ParseResult<Token> {
        let old_token = self.current_token.clone();
        self.current_token = if !self.lookahead.is_empty() {
            self.lookahead.remove(0)
        } else {
            self.lexer.next_token()?
        };
        self.current_token_id = Some(self.arena.alloc_token(self.current_token.clone()));
        Ok(old_token)
    }

    /// Expect a specific token type and consume it
    fn expect_token(&mut self, expected: TokenType) -> ParseResult<Token> {
        if self.current_token.token_type == expected {
            self.consume_token()
        } else {
            Err(ParseError::at_position(
                format!(
                    "Expected {:?}, found {:?} '{}'",
                    expected, self.current_token.token_type, self.current_token.image
                ),
                self.current_token.begin_offset
            ))
        }
    }

    /// Allocate the current token to the arena and track its ID
    fn alloc_current_token(&mut self) -> TokenId {
        let token_id = self.arena.alloc_token(self.current_token.clone());
        self.current_token_id = Some(token_id);
        token_id
    }

    /// Get lookahead token at position n (0 = current token)
    #[allow(dead_code)]
    fn lookahead(&mut self, n: usize) -> ParseResult<&Token> {
        if n == 0 {
            return Ok(&self.current_token);
        }

        // Ensure we have enough lookahead tokens
        while self.lookahead.len() < n {
            let token = self.lexer.next_token()?;
            self.lookahead.push(token);
        }

        Ok(&self.lookahead[n - 1])
    }
}
