//! Arena allocator for AST nodes. Generated by CongoCC Parser Generator. Do not edit.

use crate::tokens::Token;

/// Type-safe index for nodes in the arena
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NodeId(pub usize);

/// Type-safe index for tokens in the arena
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TokenId(pub usize);

/// Arena that owns all AST nodes and tokens
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Arena {
    /// All AST nodes
    nodes: Vec<AstNode>,
    /// All tokens
    tokens: Vec<Token>,
}

impl Arena {
    /// Create a new empty arena
    pub fn new() -> Self {
        Arena {
            nodes: Vec::new(),
            tokens: Vec::new(),
        }
    }

    /// Allocate a new node in the arena
    pub fn alloc_node(&mut self, node: AstNode) -> NodeId {
        let id = NodeId(self.nodes.len());
        self.nodes.push(node);
        id
    }

    /// Get a reference to a node
    pub fn get_node(&self, id: NodeId) -> &AstNode {
        &self.nodes[id.0]
    }

    /// Get a mutable reference to a node
    pub fn get_node_mut(&mut self, id: NodeId) -> &mut AstNode {
        &mut self.nodes[id.0]
    }

    /// Allocate a new token in the arena
    pub fn alloc_token(&mut self, token: Token) -> TokenId {
        let id = TokenId(self.tokens.len());
        self.tokens.push(token);
        id
    }

    /// Get a reference to a token
    pub fn get_token(&self, id: TokenId) -> &Token {
        &self.tokens[id.0]
    }

    /// Pretty print the AST starting from the given node
    pub fn pretty_print(&self, root: NodeId, indent: usize, input: &str) -> String {
        let mut result = format!("AST: \"{}\"\n", input);
        self.pretty_print_impl(root, indent + 1, &mut result);
        result
    }

    /// Check if a node is a pass-through (single child, no semantic value)
    fn is_passthrough(&self, node_id: NodeId) -> bool {
        match self.get_node(node_id) {
            AstNode::SqlExpression(n) => n.children.len() == 1,
            AstNode::OrExpression(n) => n.children.len() == 1,
            AstNode::AndExpression(n) => n.children.len() == 1,
            AstNode::NotExpression(n) => n.children.len() == 1 && !n.is_negated,
            AstNode::ComparisonExpression(n) => n.children.len() == 1 && n.comparison_op.is_none(),
            AstNode::ValueList(n) => n.children.len() == 1,
            AstNode::AdditiveExpression(n) => n.children.len() == 1 && n.operators.is_empty(),
            AstNode::MultiplicativeExpression(n) => n.children.len() == 1 && n.operators.is_empty(),
            AstNode::UnaryExpression(n) => n.children.len() == 1 && !n.is_negated,
            AstNode::PrimaryExpression(_) => false,
        }
    }

    /// Get the first child of a node (if any)
    fn first_child(&self, node_id: NodeId) -> Option<NodeId> {
        match self.get_node(node_id) {
            AstNode::SqlExpression(n) => n.children.first().copied(),
            AstNode::OrExpression(n) => n.children.first().copied(),
            AstNode::AndExpression(n) => n.children.first().copied(),
            AstNode::NotExpression(n) => n.children.first().copied(),
            AstNode::ComparisonExpression(n) => n.children.first().copied(),
            AstNode::ValueList(n) => n.children.first().copied(),
            AstNode::AdditiveExpression(n) => n.children.first().copied(),
            AstNode::MultiplicativeExpression(n) => n.children.first().copied(),
            AstNode::UnaryExpression(n) => n.children.first().copied(),
            AstNode::PrimaryExpression(n) => n.children.first().copied(),
        }
    }

    fn pretty_print_impl(&self, node_id: NodeId, indent: usize, result: &mut String) {
        // Skip pass-through nodes
        if self.is_passthrough(node_id) {
            if let Some(child) = self.first_child(node_id) {
                self.pretty_print_impl(child, indent, result);
            }
            return;
        }

        let indent_str = "  ".repeat(indent);
        match self.get_node(node_id) {
            AstNode::SqlExpression(node) => {
                if node.children.is_empty() {
                    let value = &self.get_token(node.begin_token).image;
                    result.push_str(&format!("{}SqlExpression(\"{}\")\n", indent_str, value));
                } else {
                    result.push_str(&format!("{}SqlExpression\n", indent_str));
                    for child in &node.children {
                        self.pretty_print_impl(*child, indent + 1, result);
                    }
                }
            }
            AstNode::OrExpression(node) => {
                if node.children.len() > 1 {
                    result.push_str(&format!("{}OrExpression [OR x{}]\n", indent_str, node.children.len() - 1));
                } else {
                    result.push_str(&format!("{}OrExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::AndExpression(node) => {
                if node.children.len() > 1 {
                    result.push_str(&format!("{}AndExpression [AND x{}]\n", indent_str, node.children.len() - 1));
                } else {
                    result.push_str(&format!("{}AndExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::NotExpression(node) => {
                if node.is_negated {
                    result.push_str(&format!("{}NotExpression [NOT]\n", indent_str));
                } else {
                    result.push_str(&format!("{}NotExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::ComparisonExpression(node) => {
                if let Some(op) = &node.comparison_op {
                    let op_str = match op {
                        ComparisonOp::Eq => "=",
                        ComparisonOp::Ne => "!=",
                        ComparisonOp::Lt => "<",
                        ComparisonOp::Gt => ">",
                        ComparisonOp::Le => "<=",
                        ComparisonOp::Ge => ">=",
                        ComparisonOp::Like => "LIKE",
                        ComparisonOp::In => "IN",
                        ComparisonOp::Between => "BETWEEN",
                        ComparisonOp::IsNull => "IS NULL",
                        ComparisonOp::IsNotNull => "IS NOT NULL",
                    };
                    result.push_str(&format!("{}ComparisonExpression [{}]\n", indent_str, op_str));
                } else {
                    result.push_str(&format!("{}ComparisonExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::ValueList(node) => {
                if node.children.len() > 1 {
                    result.push_str(&format!("{}ValueList [COMMA x{}]\n", indent_str, node.children.len() - 1));
                } else {
                    result.push_str(&format!("{}ValueList\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::AdditiveExpression(node) => {
                if !node.operators.is_empty() {
                    let ops: Vec<&str> = node.operators.iter()
                        .map(|op| match op {
                            AdditiveOp::Add => "+",
                            AdditiveOp::Sub => "-",
                        })
                        .collect();
                    result.push_str(&format!("{}AdditiveExpression [{}]\n", indent_str, ops.join(", ")));
                } else {
                    result.push_str(&format!("{}AdditiveExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::MultiplicativeExpression(node) => {
                if !node.operators.is_empty() {
                    let ops: Vec<&str> = node.operators.iter()
                        .map(|op| match op {
                            MultiplicativeOp::Mul => "*",
                            MultiplicativeOp::Div => "/",
                        })
                        .collect();
                    result.push_str(&format!("{}MultiplicativeExpression [{}]\n", indent_str, ops.join(", ")));
                } else {
                    result.push_str(&format!("{}MultiplicativeExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::UnaryExpression(node) => {
                if node.is_negated {
                    result.push_str(&format!("{}UnaryExpression [MINUS]\n", indent_str));
                } else {
                    result.push_str(&format!("{}UnaryExpression\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
            }
            AstNode::PrimaryExpression(node) => {
                if node.children.is_empty() {
                    let token = self.get_token(node.begin_token);
                    result.push_str(&format!("{}PrimaryExpression(\"{}\")\n", indent_str, token.image));
                } else {
                    result.push_str(&format!("{}PrimaryExpression\n", indent_str));
                    for child in &node.children {
                        self.pretty_print_impl(*child, indent + 1, result);
                    }
                }
            }
        }
    }
}

impl Default for Arena {
    fn default() -> Self {
        Self::new()
    }
}

/// Enum containing all AST node types
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum AstNode {
    /// AST node: SqlExpression
    SqlExpression(SqlExpressionNode),
    /// AST node: OrExpression
    OrExpression(OrExpressionNode),
    /// AST node: AndExpression
    AndExpression(AndExpressionNode),
    /// AST node: NotExpression
    NotExpression(NotExpressionNode),
    /// AST node: ComparisonExpression
    ComparisonExpression(ComparisonExpressionNode),
    /// AST node: ValueList
    ValueList(ValueListNode),
    /// AST node: AdditiveExpression
    AdditiveExpression(AdditiveExpressionNode),
    /// AST node: MultiplicativeExpression
    MultiplicativeExpression(MultiplicativeExpressionNode),
    /// AST node: UnaryExpression
    UnaryExpression(UnaryExpressionNode),
    /// AST node: PrimaryExpression
    PrimaryExpression(PrimaryExpressionNode),
}

/// Comparison operation type for ComparisonExpression
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ComparisonOp {
    /// =
    Eq,
    /// !=
    Ne,
    /// <
    Lt,
    /// >
    Gt,
    /// <=
    Le,
    /// >=
    Ge,
    /// LIKE
    Like,
    /// IN
    In,
    /// BETWEEN
    Between,
    /// IS NULL
    IsNull,
    /// IS NOT NULL
    IsNotNull,
}

/// Operator for AdditiveExpression
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum AdditiveOp {
    /// +
    Add,
    /// -
    Sub,
}

/// Operator for MultiplicativeExpression
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum MultiplicativeOp {
    /// *
    Mul,
    /// /
    Div,
}

/// AST node for SqlExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SqlExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl SqlExpressionNode {
    /// Create a new SqlExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        SqlExpressionNode {
            parent: None,
            children: Vec::new(),
            begin_token,
            end_token,
        }
    }

}

/// AST node for OrExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct OrExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl OrExpressionNode {
    /// Create a new OrExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        OrExpressionNode {
            parent: None,
            children: Vec::new(),
            begin_token,
            end_token,
        }
    }

}

/// AST node for AndExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AndExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl AndExpressionNode {
    /// Create a new AndExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        AndExpressionNode {
            parent: None,
            children: Vec::new(),
            begin_token,
            end_token,
        }
    }

}

/// AST node for NotExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NotExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// Whether the NOT operator was present
    pub is_negated: bool,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl NotExpressionNode {
    /// Create a new NotExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        NotExpressionNode {
            parent: None,
            children: Vec::new(),
            is_negated: false,
            begin_token,
            end_token,
        }
    }

}

/// AST node for ComparisonExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ComparisonExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// The comparison operator used, if any
    pub comparison_op: Option<ComparisonOp>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl ComparisonExpressionNode {
    /// Create a new ComparisonExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        ComparisonExpressionNode {
            parent: None,
            children: Vec::new(),
            comparison_op: None,
            begin_token,
            end_token,
        }
    }

}

/// AST node for ValueList production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ValueListNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl ValueListNode {
    /// Create a new ValueList node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        ValueListNode {
            parent: None,
            children: Vec::new(),
            begin_token,
            end_token,
        }
    }

}

/// AST node for AdditiveExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AdditiveExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// Operators between children: operators[i] is between children[i] and children[i+1]
    pub operators: Vec<AdditiveOp>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl AdditiveExpressionNode {
    /// Create a new AdditiveExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        AdditiveExpressionNode {
            parent: None,
            children: Vec::new(),
            operators: Vec::new(),
            begin_token,
            end_token,
        }
    }

    /// Get the left operand (first child)
    pub fn left<'a>(&self, arena: &'a Arena) -> &'a AstNode {
        arena.get_node(self.children[0])
    }

    /// Get the right operand (second child for binary case)
    pub fn right<'a>(&self, arena: &'a Arena) -> Option<&'a AstNode> {
        self.children.get(1).map(|id| arena.get_node(*id))
    }

    /// Get operator at index (between children[i] and children[i+1])
    pub fn op(&self, index: usize) -> Option<AdditiveOp> {
        self.operators.get(index).copied()
    }

    /// Get first operator (for binary expressions)
    pub fn first_op(&self) -> Option<AdditiveOp> {
        self.operators.first().copied()
    }

    /// Iterator over (operator, operand) pairs after the first operand
    pub fn op_operand_pairs(&self) -> impl Iterator<Item = (AdditiveOp, NodeId)> + '_ {
        self.operators.iter().copied().zip(self.children.iter().skip(1).copied())
    }
}

/// AST node for MultiplicativeExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MultiplicativeExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// Operators between children: operators[i] is between children[i] and children[i+1]
    pub operators: Vec<MultiplicativeOp>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl MultiplicativeExpressionNode {
    /// Create a new MultiplicativeExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        MultiplicativeExpressionNode {
            parent: None,
            children: Vec::new(),
            operators: Vec::new(),
            begin_token,
            end_token,
        }
    }

    /// Get the left operand (first child)
    pub fn left<'a>(&self, arena: &'a Arena) -> &'a AstNode {
        arena.get_node(self.children[0])
    }

    /// Get the right operand (second child for binary case)
    pub fn right<'a>(&self, arena: &'a Arena) -> Option<&'a AstNode> {
        self.children.get(1).map(|id| arena.get_node(*id))
    }

    /// Get operator at index (between children[i] and children[i+1])
    pub fn op(&self, index: usize) -> Option<MultiplicativeOp> {
        self.operators.get(index).copied()
    }

    /// Get first operator (for binary expressions)
    pub fn first_op(&self) -> Option<MultiplicativeOp> {
        self.operators.first().copied()
    }

    /// Iterator over (operator, operand) pairs after the first operand
    pub fn op_operand_pairs(&self) -> impl Iterator<Item = (MultiplicativeOp, NodeId)> + '_ {
        self.operators.iter().copied().zip(self.children.iter().skip(1).copied())
    }
}

/// AST node for UnaryExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UnaryExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// Whether the MINUS operator was present
    pub is_negated: bool,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl UnaryExpressionNode {
    /// Create a new UnaryExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        UnaryExpressionNode {
            parent: None,
            children: Vec::new(),
            is_negated: false,
            begin_token,
            end_token,
        }
    }

}

/// AST node for PrimaryExpression production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PrimaryExpressionNode {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl PrimaryExpressionNode {
    /// Create a new PrimaryExpression node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        PrimaryExpressionNode {
            parent: None,
            children: Vec::new(),
            begin_token,
            end_token,
        }
    }

    /// Get the token image (the actual value as string)
    pub fn value<'a>(&self, arena: &'a Arena) -> &'a str {
        &arena.get_token(self.begin_token).image
    }
}

