//! Parser implementation. Generated by CongoCC Parser Generator. Do not edit.

use crate::error::{ParseError, ParseResult};
use crate::tokens::{Token, TokenType};
use crate::lexer::Lexer;
use crate::arena::{Arena, AstNode, NodeId, TokenId};
use crate::arena::ComparisonOp;
use crate::arena::AdditiveOp;
use crate::arena::MultiplicativeOp;
use crate::arena::{
    SqlExpressionNode,
    OrExpressionNode,
    AndExpressionNode,
    NotExpressionNode,
    ComparisonExpressionNode,
    ValueListNode,
    AdditiveExpressionNode,
    MultiplicativeExpressionNode,
    UnaryExpressionNode,
    PrimaryExpressionNode
};

/// The parser for SqlExprParser
pub struct Parser {
    /// The lexer providing tokens
    lexer: Lexer,
    /// Current token being examined
    current_token: Token,
    /// Lookahead tokens
    lookahead: Vec<Token>,
    /// Arena owning all AST nodes and tokens
    arena: Arena,
    /// ID of the most recently allocated token
    current_token_id: Option<TokenId>,
    /// Original input string
    input: String,
}

impl Parser {
    /// Create a new parser for the given input
    pub fn new(input: String) -> ParseResult<Self> {
        let mut lexer = Lexer::new(input.clone());
        let current_token = lexer.next_token()?;

        Ok(Parser {
            lexer,
            current_token,
            lookahead: Vec::new(),
            arena: Arena::new(),
            current_token_id: None,
            input,
        })
    }

    /// Get a reference to the arena containing all AST nodes
    pub fn arena(&self) -> &Arena {
        &self.arena
    }

    /// Get a mutable reference to the arena
    pub fn arena_mut(&mut self) -> &mut Arena {
        &mut self.arena
    }

    /// Get the original input string
    pub fn input(&self) -> &str {
        &self.input
    }

    /// Parse the input and return the root node ID
    pub fn parse(&mut self) -> ParseResult<NodeId> {
        self.parse_sql_expression()
    }

    /// Parse: SqlExpression -> OrExpression <EOF>
    fn parse_sql_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();

        let child = self.parse_or_expression()?;

        self.expect_token(TokenType::EOF)?;
        let end_token = self.current_token_id.unwrap_or(begin_token);

        let mut node = SqlExpressionNode::new(begin_token, end_token);
        node.children.push(child);

        let node_id = self.arena.alloc_node(AstNode::SqlExpression(node));
        self.set_parent(child, node_id);
        Ok(node_id)
    }

    /// Parse: OrExpression -> AndExpression (OR AndExpression)*
    fn parse_or_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();

        let first = self.parse_and_expression()?;
        children.push(first);

        while self.current_token.token_type == TokenType::OR {
            self.consume_token()?;
            let child = self.parse_and_expression()?;
            children.push(child);
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = OrExpressionNode::new(begin_token, end_token);
        node.children = children.clone();

        let node_id = self.arena.alloc_node(AstNode::OrExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: AndExpression -> NotExpression (AND NotExpression)*
    fn parse_and_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();

        let first = self.parse_not_expression()?;
        children.push(first);

        while self.current_token.token_type == TokenType::AND {
            self.consume_token()?;
            let child = self.parse_not_expression()?;
            children.push(child);
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = AndExpressionNode::new(begin_token, end_token);
        node.children = children.clone();

        let node_id = self.arena.alloc_node(AstNode::AndExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: NotExpression -> NOT NotExpression | ComparisonExpression
    fn parse_not_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();

        if self.current_token.token_type == TokenType::NOT {
            self.consume_token()?;
            let child = self.parse_not_expression()?;
            let end_token = self.current_token_id.unwrap_or(begin_token);

            let mut node = NotExpressionNode::new(begin_token, end_token);
            node.is_negated = true;
            node.children.push(child);

            let node_id = self.arena.alloc_node(AstNode::NotExpression(node));
            self.set_parent(child, node_id);
            return Ok(node_id);
        }

        let child = self.parse_comparison_expression()?;
        let end_token = self.current_token_id.unwrap_or(begin_token);

        let mut node = NotExpressionNode::new(begin_token, end_token);
        node.children.push(child);

        let node_id = self.arena.alloc_node(AstNode::NotExpression(node));
        self.set_parent(child, node_id);
        Ok(node_id)
    }

    /// Parse: ComparisonExpression -> AdditiveExpression (suffix)?
    fn parse_comparison_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();
        let mut comparison_op = None;

        let left = self.parse_additive_expression()?;
        children.push(left);

        // Check for optional suffix
        match self.current_token.token_type {
            TokenType::EQ => {
                comparison_op = Some(ComparisonOp::Eq);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::NE => {
                comparison_op = Some(ComparisonOp::Ne);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::LT => {
                comparison_op = Some(ComparisonOp::Lt);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::GT => {
                comparison_op = Some(ComparisonOp::Gt);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::LE => {
                comparison_op = Some(ComparisonOp::Le);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::GE => {
                comparison_op = Some(ComparisonOp::Ge);
                self.consume_token()?;
                let right = self.parse_additive_expression()?;
                children.push(right);
            }
            TokenType::LIKE => {
                comparison_op = Some(ComparisonOp::Like);
                self.consume_token()?;
                self.expect_token(TokenType::STRING_LITERAL)?;
            }
            TokenType::IN => {
                comparison_op = Some(ComparisonOp::In);
                self.consume_token()?;
                self.expect_token(TokenType::LPAREN)?;
                let child = self.parse_value_list()?;
                children.push(child);
                self.expect_token(TokenType::RPAREN)?;
            }
            TokenType::BETWEEN => {
                comparison_op = Some(ComparisonOp::Between);
                self.consume_token()?;
                let child = self.parse_additive_expression()?;
                children.push(child);
                self.expect_token(TokenType::AND)?;
                let child = self.parse_additive_expression()?;
                children.push(child);
            }
            TokenType::IS => {
                self.consume_token()?;
                if self.current_token.token_type == TokenType::NOT {
                    self.consume_token()?;
                    self.expect_token(TokenType::NULL)?;
                    comparison_op = Some(ComparisonOp::IsNotNull);
                } else {
                    self.expect_token(TokenType::NULL)?;
                    comparison_op = Some(ComparisonOp::IsNull);
                }
            }
            _ => {}
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = ComparisonExpressionNode::new(begin_token, end_token);
        node.comparison_op = comparison_op;
        node.children = children.clone();

        let node_id = self.arena.alloc_node(AstNode::ComparisonExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: ValueList -> AdditiveExpression (COMMA AdditiveExpression)*
    fn parse_value_list(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();

        let first = self.parse_additive_expression()?;
        children.push(first);

        while self.current_token.token_type == TokenType::COMMA {
            self.consume_token()?;
            let child = self.parse_additive_expression()?;
            children.push(child);
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = ValueListNode::new(begin_token, end_token);
        node.children = children.clone();

        let node_id = self.arena.alloc_node(AstNode::ValueList(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: AdditiveExpression -> MultiplicativeExpression ((ops) MultiplicativeExpression)*
    fn parse_additive_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();
        let mut operators = Vec::new();

        let first = self.parse_multiplicative_expression()?;
        children.push(first);

        while self.current_token.token_type == TokenType::PLUS
            || self.current_token.token_type == TokenType::MINUS
        {
            let op = match self.current_token.token_type {
                TokenType::PLUS => AdditiveOp::Add,
                TokenType::MINUS => AdditiveOp::Sub,
                _ => unreachable!(),
            };
            operators.push(op);

            self.consume_token()?;
            let child = self.parse_multiplicative_expression()?;
            children.push(child);
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = AdditiveExpressionNode::new(begin_token, end_token);
        node.children = children.clone();
        node.operators = operators;

        let node_id = self.arena.alloc_node(AstNode::AdditiveExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: MultiplicativeExpression -> UnaryExpression ((ops) UnaryExpression)*
    fn parse_multiplicative_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();
        let mut operators = Vec::new();

        let first = self.parse_unary_expression()?;
        children.push(first);

        while self.current_token.token_type == TokenType::STAR
            || self.current_token.token_type == TokenType::SLASH
        {
            let op = match self.current_token.token_type {
                TokenType::STAR => MultiplicativeOp::Mul,
                TokenType::SLASH => MultiplicativeOp::Div,
                _ => unreachable!(),
            };
            operators.push(op);

            self.consume_token()?;
            let child = self.parse_unary_expression()?;
            children.push(child);
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = MultiplicativeExpressionNode::new(begin_token, end_token);
        node.children = children.clone();
        node.operators = operators;

        let node_id = self.arena.alloc_node(AstNode::MultiplicativeExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    /// Parse: UnaryExpression -> MINUS UnaryExpression | PrimaryExpression
    fn parse_unary_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();

        if self.current_token.token_type == TokenType::MINUS {
            self.consume_token()?;
            let child = self.parse_unary_expression()?;
            let end_token = self.current_token_id.unwrap_or(begin_token);

            let mut node = UnaryExpressionNode::new(begin_token, end_token);
            node.is_negated = true;
            node.children.push(child);

            let node_id = self.arena.alloc_node(AstNode::UnaryExpression(node));
            self.set_parent(child, node_id);
            return Ok(node_id);
        }

        let child = self.parse_primary_expression()?;
        let end_token = self.current_token_id.unwrap_or(begin_token);

        let mut node = UnaryExpressionNode::new(begin_token, end_token);
        node.children.push(child);

        let node_id = self.arena.alloc_node(AstNode::UnaryExpression(node));
        self.set_parent(child, node_id);
        Ok(node_id)
    }

    /// Parse: PrimaryExpression
    #[allow(clippy::if_same_then_else)]
    fn parse_primary_expression(&mut self) -> ParseResult<NodeId> {
        let begin_token = self.alloc_current_token();
        let mut children = Vec::new();

        if self.current_token.token_type == TokenType::INTEGER_LITERAL {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::DECIMAL_LITERAL {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::STRING_LITERAL {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::TRUE {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::FALSE {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::NULL {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::IDENTIFIER {
            self.consume_token()?;
        }
        else if self.current_token.token_type == TokenType::LPAREN {
            self.consume_token()?;
            let inner = self.parse_or_expression()?;
            children.push(inner);
            self.expect_token(TokenType::RPAREN)?;
        }
        else {
            return Err(ParseError::at_position(
                format!(
                    "Expected expression, found {:?} '{}'",
                    self.current_token.token_type, self.current_token.image
                ),
                self.current_token.begin_offset,
            ));
        }

        let end_token = self.current_token_id.unwrap_or(begin_token);
        let mut node = PrimaryExpressionNode::new(begin_token, end_token);
        node.children = children.clone();

        let node_id = self.arena.alloc_node(AstNode::PrimaryExpression(node));
        for child in children {
            self.set_parent(child, node_id);
        }
        Ok(node_id)
    }

    // ========== Helper Methods ==========

    /// Set the parent of a node
    fn set_parent(&mut self, child_id: NodeId, parent_id: NodeId) {
        match self.arena.get_node_mut(child_id) {
            AstNode::SqlExpression(node) => node.parent = Some(parent_id),
            AstNode::OrExpression(node) => node.parent = Some(parent_id),
            AstNode::AndExpression(node) => node.parent = Some(parent_id),
            AstNode::NotExpression(node) => node.parent = Some(parent_id),
            AstNode::ComparisonExpression(node) => node.parent = Some(parent_id),
            AstNode::ValueList(node) => node.parent = Some(parent_id),
            AstNode::AdditiveExpression(node) => node.parent = Some(parent_id),
            AstNode::MultiplicativeExpression(node) => node.parent = Some(parent_id),
            AstNode::UnaryExpression(node) => node.parent = Some(parent_id),
            AstNode::PrimaryExpression(node) => node.parent = Some(parent_id),
        }
    }

    /// Check if the current token matches any of the given types
    #[allow(dead_code)]
    fn current_token_matches(&self, types: &[TokenType]) -> bool {
        types.contains(&self.current_token.token_type)
    }

    /// Consume the current token and advance to the next one
    fn consume_token(&mut self) -> ParseResult<Token> {
        let old_token = self.current_token.clone();
        self.current_token = if !self.lookahead.is_empty() {
            self.lookahead.remove(0)
        } else {
            self.lexer.next_token()?
        };
        self.current_token_id = Some(self.arena.alloc_token(self.current_token.clone()));
        Ok(old_token)
    }

    /// Expect a specific token type and consume it
    fn expect_token(&mut self, expected: TokenType) -> ParseResult<Token> {
        if self.current_token.token_type == expected {
            self.consume_token()
        } else {
            Err(ParseError::at_position(
                format!(
                    "Expected {:?}, found {:?} '{}'",
                    expected, self.current_token.token_type, self.current_token.image
                ),
                self.current_token.begin_offset
            ))
        }
    }

    /// Allocate the current token to the arena and track its ID
    fn alloc_current_token(&mut self) -> TokenId {
        let token_id = self.arena.alloc_token(self.current_token.clone());
        self.current_token_id = Some(token_id);
        token_id
    }

    /// Get lookahead token at position n (0 = current token)
    #[allow(dead_code)]
    fn lookahead(&mut self, n: usize) -> ParseResult<&Token> {
        if n == 0 {
            return Ok(&self.current_token);
        }

        // Ensure we have enough lookahead tokens
        while self.lookahead.len() < n {
            let token = self.lexer.next_token()?;
            self.lookahead.push(token);
        }

        Ok(&self.lookahead[n - 1])
    }
}
