//! Token types and definitions. Generated by CongoCC Parser Generator. Do not edit.

use std::fmt;

/// Token type enumeration
///
/// Represents all possible token types recognized by the lexer.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    /// Token: EOF
        EOF,
    /// Token: AND
        AND,
    /// Token: OR
        OR,
    /// Token: NOT
        NOT,
    /// Token: TRUE
        TRUE,
    /// Token: FALSE
        FALSE,
    /// Token: NULL
        NULL,
    /// Token: LIKE
        LIKE,
    /// Token: IN
        IN,
    /// Token: BETWEEN
        BETWEEN,
    /// Token: IS
        IS,
    /// Token: EQ
        EQ,
    /// Token: LT
        LT,
    /// Token: GT
        GT,
    /// Token: LE
        LE,
    /// Token: GE
        GE,
    /// Token: PLUS
        PLUS,
    /// Token: MINUS
        MINUS,
    /// Token: STAR
        STAR,
    /// Token: SLASH
        SLASH,
    /// Token: LPAREN
        LPAREN,
    /// Token: RPAREN
        RPAREN,
    /// Token: COMMA
        COMMA,
    /// Token: _TOKEN_23
        Token23,
    /// Token: _TOKEN_24
        Token24,
    /// Token: _TOKEN_25
        Token25,
    /// Token: _TOKEN_26
        Token26,
    /// Token: NE
        NE,
    /// Token: INTEGER_LITERAL
        INTEGER_LITERAL,
    /// Token: DECIMAL_LITERAL
        DECIMAL_LITERAL,
    /// Token: STRING_LITERAL
        STRING_LITERAL,
    /// Token: IDENTIFIER
        IDENTIFIER,
    /// Invalid token marker
    INVALID,
}

impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenType::EOF => write!(f, "EOF"),
            TokenType::AND => write!(f, "AND"),
            TokenType::OR => write!(f, "OR"),
            TokenType::NOT => write!(f, "NOT"),
            TokenType::TRUE => write!(f, "TRUE"),
            TokenType::FALSE => write!(f, "FALSE"),
            TokenType::NULL => write!(f, "NULL"),
            TokenType::LIKE => write!(f, "LIKE"),
            TokenType::IN => write!(f, "IN"),
            TokenType::BETWEEN => write!(f, "BETWEEN"),
            TokenType::IS => write!(f, "IS"),
            TokenType::EQ => write!(f, "EQ"),
            TokenType::LT => write!(f, "LT"),
            TokenType::GT => write!(f, "GT"),
            TokenType::LE => write!(f, "LE"),
            TokenType::GE => write!(f, "GE"),
            TokenType::PLUS => write!(f, "PLUS"),
            TokenType::MINUS => write!(f, "MINUS"),
            TokenType::STAR => write!(f, "STAR"),
            TokenType::SLASH => write!(f, "SLASH"),
            TokenType::LPAREN => write!(f, "LPAREN"),
            TokenType::RPAREN => write!(f, "RPAREN"),
            TokenType::COMMA => write!(f, "COMMA"),
            TokenType::Token23 => write!(f, "_TOKEN_23"),
            TokenType::Token24 => write!(f, "_TOKEN_24"),
            TokenType::Token25 => write!(f, "_TOKEN_25"),
            TokenType::Token26 => write!(f, "_TOKEN_26"),
            TokenType::NE => write!(f, "NE"),
            TokenType::INTEGER_LITERAL => write!(f, "INTEGER_LITERAL"),
            TokenType::DECIMAL_LITERAL => write!(f, "DECIMAL_LITERAL"),
            TokenType::STRING_LITERAL => write!(f, "STRING_LITERAL"),
            TokenType::IDENTIFIER => write!(f, "IDENTIFIER"),
            TokenType::INVALID => write!(f, "INVALID"),
        }
    }
}

/// Lexical state enumeration
///
/// Represents different lexical states the lexer can be in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LexicalState {
    /// Lexical state: DEFAULT
    DEFAULT,
}

/// A single token in the input stream
///
/// Tokens are the atomic units produced by the lexer. Each token has:
/// - A type (e.g., INTEGER, PLUS, EOF)
/// - An image (the actual text matched)
/// - Position information (begin/end offsets)
/// - Optional links to previous/next tokens
#[derive(Debug, Clone)]
pub struct Token {
    /// The type of this token
    pub token_type: TokenType,
    /// The actual text of this token
    pub image: String,
    /// Absolute offset in the input where this token begins
    pub begin_offset: usize,
    /// Absolute offset in the input where this token ends
    pub end_offset: usize,
    /// Index of the next token (if any)
    pub next: Option<usize>,
    /// Index of the previous token (if any)
    pub previous: Option<usize>,
}

impl Token {
    /// Create a new token
    pub fn new(
        token_type: TokenType,
        image: String,
        begin_offset: usize,
        end_offset: usize,
    ) -> Self {
        Token {
            token_type,
            image,
            begin_offset,
            end_offset,
            next: None,
            previous: None,
        }
    }

    /// Get the length of this token in characters
    pub fn len(&self) -> usize {
        self.end_offset.saturating_sub(self.begin_offset)
    }

    /// Check if this token is empty
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Check if this token is of a specific type
    pub fn is_type(&self, token_type: TokenType) -> bool {
        self.token_type == token_type
    }

    /// Check if this token is one of the specified types
    pub fn is_one_of(&self, types: &[TokenType]) -> bool {
        types.contains(&self.token_type)
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: \"{}\"", self.token_type, self.image)
    }
}

/// Token source trait for tracking token locations
pub trait TokenSource {
    /// Get the line number for a given offset
    fn get_line_from_offset(&self, offset: usize) -> usize;

    /// Get the column number for a given offset
    fn get_column_from_offset(&self, offset: usize) -> usize;
}
