//! Arena allocator for AST nodes. Generated by ${generated_by}. Do not edit.

use crate::tokens::Token;

/// Type-safe index for nodes in the arena
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NodeId(pub usize);

/// Type-safe index for tokens in the arena
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TokenId(pub usize);

/// Arena that owns all AST nodes and tokens
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Arena {
    /// All AST nodes
    nodes: Vec<AstNode>,
    /// All tokens
    tokens: Vec<Token>,
}

impl Arena {
    /// Create a new empty arena
    pub fn new() -> Self {
        Arena {
            nodes: Vec::new(),
            tokens: Vec::new(),
        }
    }

    /// Allocate a new node in the arena
    pub fn alloc_node(&mut self, node: AstNode) -> NodeId {
        let id = NodeId(self.nodes.len());
        self.nodes.push(node);
        id
    }

    /// Get a reference to a node
    pub fn get_node(&self, id: NodeId) -> &AstNode {
        &self.nodes[id.0]
    }

    /// Get a mutable reference to a node
    pub fn get_node_mut(&mut self, id: NodeId) -> &mut AstNode {
        &mut self.nodes[id.0]
    }

    /// Allocate a new token in the arena
    pub fn alloc_token(&mut self, token: Token) -> TokenId {
        let id = TokenId(self.tokens.len());
        self.tokens.push(token);
        id
    }

    /// Get a reference to a token
    pub fn get_token(&self, id: TokenId) -> &Token {
        &self.tokens[id.0]
    }

[#if grammar.productionTable?size > 0]
    /// Pretty print the AST starting from the given node
    pub fn pretty_print(&self, root: NodeId, indent: usize, input: &str) -> String {
        let mut result = format!("AST: \"{}\"\n", input);
        self.pretty_print_impl(root, indent + 1, &mut result);
        result
    }

    /// Check if a node is a pass-through (single child, no semantic value)
    fn is_passthrough(&self, node_id: NodeId) -> bool {
        match self.get_node(node_id) {
[#list grammar.parserProductions as production]
[#var info = globals::analyzeRustProduction(production)]
[#if info.pattern == "root"]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1,
[#elseif info.pattern == "infix"]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1 && n.operators.is_empty(),
[#elseif info.pattern == "separator"]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1,
[#elseif info.pattern == "prefix"]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1 && !n.${info.boolFieldName},
[#elseif info.pattern == "optional_suffix" && info.hasSuffixEnum]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1 && n.comparison_op.is_none(),
[#elseif info.pattern == "choice"]
            AstNode::${production.name?cap_first}(_) => false,
[#else]
            AstNode::${production.name?cap_first}(n) => n.children.len() == 1,
[/#if]
[/#list]
        }
    }

    /// Get the first child of a node (if any)
    fn first_child(&self, node_id: NodeId) -> Option<NodeId> {
        match self.get_node(node_id) {
[#list grammar.parserProductions as production]
            AstNode::${production.name?cap_first}(n) => n.children.first().copied(),
[/#list]
        }
    }

    fn pretty_print_impl(&self, node_id: NodeId, indent: usize, result: &mut String) {
        // Skip pass-through nodes
        if self.is_passthrough(node_id) {
            if let Some(child) = self.first_child(node_id) {
                self.pretty_print_impl(child, indent, result);
            }
            return;
        }

        let indent_str = "  ".repeat(indent);
        match self.get_node(node_id) {
[#list grammar.parserProductions as production]
[#var info = globals::analyzeRustProduction(production)]
            AstNode::${production.name?cap_first}(node) => {
[#if info.pattern == "infix"]
                if !node.operators.is_empty() {
                    let ops: Vec<&str> = node.operators.iter()
                        .map(|op| match op {
[#list info.operatorVariants as v]
                            ${info.operatorEnumName}::${v.variantName} => "${v.display}",
[/#list]
                        })
                        .collect();
                    result.push_str(&format!("{}${production.name?cap_first} [{}]\n", indent_str, ops.join(", ")));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
[#elseif info.pattern == "separator"]
                if node.children.len() > 1 {
                    result.push_str(&format!("{}${production.name?cap_first} [${info.separatorTokenName} x{}]\n", indent_str, node.children.len() - 1));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
[#elseif info.pattern == "prefix"]
                if node.${info.boolFieldName} {
                    result.push_str(&format!("{}${production.name?cap_first} [${info.prefixTokenName}]\n", indent_str));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
[#elseif info.pattern == "optional_suffix" && info.hasSuffixEnum]
                if let Some(op) = &node.comparison_op {
                    let op_str = match op {
[#list info.suffixVariants as v]
                        ${info.suffixEnumName}::${v.variantName} => "${v.display}",
[/#list]
                    };
                    result.push_str(&format!("{}${production.name?cap_first} [{}]\n", indent_str, op_str));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                }
                for child in &node.children {
                    self.pretty_print_impl(*child, indent + 1, result);
                }
[#elseif info.pattern == "choice"]
                if node.children.is_empty() {
                    let token = self.get_token(node.begin_token);
                    result.push_str(&format!("{}${production.name?cap_first}(\"{}\")\n", indent_str, token.image));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                    for child in &node.children {
                        self.pretty_print_impl(*child, indent + 1, result);
                    }
                }
[#else]
                if node.children.is_empty() {
                    let value = &self.get_token(node.begin_token).image;
                    result.push_str(&format!("{}${production.name?cap_first}(\"{}\")\n", indent_str, value));
                } else {
                    result.push_str(&format!("{}${production.name?cap_first}\n", indent_str));
                    for child in &node.children {
                        self.pretty_print_impl(*child, indent + 1, result);
                    }
                }
[/#if]
            }
[/#list]
        }
    }
[/#if]
}

impl Default for Arena {
    fn default() -> Self {
        Self::new()
    }
}

[#if grammar.productionTable?size > 0]
/// Enum containing all AST node types
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum AstNode {
[#list grammar.parserProductions as production]
    /// AST node: ${production.name}
    ${production.name?cap_first}(${production.name?cap_first}Node),
[/#list]
}

[#-- Generate operator enums for infix patterns --]
[#list grammar.parserProductions as production]
[#var info = globals::analyzeRustProduction(production)]
[#if info.pattern == "infix" && info.hasOperatorEnum]
/// Operator for ${production.name}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ${info.operatorEnumName} {
[#list info.operatorVariants as v]
    /// ${v.display}
    ${v.variantName},
[/#list]
}

[/#if]
[#if info.pattern == "optional_suffix" && info.hasSuffixEnum]
/// Comparison operation type for ${production.name}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum ${info.suffixEnumName} {
[#list info.suffixVariants as v]
    /// ${v.display}
    ${v.variantName},
[/#list]
}

[/#if]
[/#list]
[#-- Generate struct for each production --]
[#list grammar.parserProductions as production]
[#var info = globals::analyzeRustProduction(production)]
/// AST node for ${production.name} production
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ${production.name?cap_first}Node {
    /// Parent node (if any)
    pub parent: Option<NodeId>,
    /// Child nodes
    pub children: Vec<NodeId>,
[#if info.pattern == "infix" && info.hasOperatorEnum]
    /// Operators between children: operators[i] is between children[i] and children[i+1]
    pub operators: Vec<${info.operatorEnumName}>,
[/#if]
[#if info.pattern == "prefix" && info.hasBoolField]
    /// Whether the ${info.prefixTokenName} operator was present
    pub ${info.boolFieldName}: bool,
[/#if]
[#if info.pattern == "optional_suffix" && info.hasSuffixEnum]
    /// The comparison operator used, if any
    pub comparison_op: Option<${info.suffixEnumName}>,
[/#if]
    /// First token of this node
    pub begin_token: TokenId,
    /// Last token of this node
    pub end_token: TokenId,
}

impl ${production.name?cap_first}Node {
    /// Create a new ${production.name} node
    pub fn new(begin_token: TokenId, end_token: TokenId) -> Self {
        ${production.name?cap_first}Node {
            parent: None,
            children: Vec::new(),
[#if info.pattern == "infix" && info.hasOperatorEnum]
            operators: Vec::new(),
[/#if]
[#if info.pattern == "prefix" && info.hasBoolField]
            ${info.boolFieldName}: false,
[/#if]
[#if info.pattern == "optional_suffix" && info.hasSuffixEnum]
            comparison_op: None,
[/#if]
            begin_token,
            end_token,
        }
    }

[#if info.pattern == "infix" && info.hasOperatorEnum]
    /// Get the left operand (first child)
    pub fn left<'a>(&self, arena: &'a Arena) -> &'a AstNode {
        arena.get_node(self.children[0])
    }

    /// Get the right operand (second child for binary case)
    pub fn right<'a>(&self, arena: &'a Arena) -> Option<&'a AstNode> {
        self.children.get(1).map(|id| arena.get_node(*id))
    }

    /// Get operator at index (between children[i] and children[i+1])
    pub fn op(&self, index: usize) -> Option<${info.operatorEnumName}> {
        self.operators.get(index).copied()
    }

    /// Get first operator (for binary expressions)
    pub fn first_op(&self) -> Option<${info.operatorEnumName}> {
        self.operators.first().copied()
    }

    /// Iterator over (operator, operand) pairs after the first operand
    pub fn op_operand_pairs(&self) -> impl Iterator<Item = (${info.operatorEnumName}, NodeId)> + '_ {
        self.operators.iter().copied().zip(self.children.iter().skip(1).copied())
    }
[#elseif info.pattern == "choice"]
    /// Get the token image (the actual value as string)
    pub fn value<'a>(&self, arena: &'a Arena) -> &'a str {
        &arena.get_token(self.begin_token).image
    }
[/#if]
}

[/#list]
[/#if]
