[#--
  Lexer template for Rust code generation.

  Generates a fully functional lexer that handles:
  - Multi-character operator literals (longest match first)
  - Single-character operator literals
  - RegexpChoice tokens (e.g., NE: "<>" | "!=")
  - String literals (single-quote delimited)
  - Integer and decimal number literals
  - Identifiers with case-insensitive keyword matching
  - Whitespace skipping for SKIP tokens
--]
[#--
  Classification helpers.
  We classify regular expressions into categories for code generation:
  1. Operator literals: RegexpStringLiteral with !ignoreCase (not keywords, not skipped)
  2. Choice operators: RegexpChoice where alternatives are string literals
  3. Keywords: RegexpStringLiteral with ignoreCase
  4. IDENTIFIER token: non-literal regexp with label containing "IDENTIFIER"
  5. INTEGER/DECIMAL tokens: non-literal regexp with label containing "INTEGER" or "DECIMAL"
  6. STRING_LITERAL token: non-literal regexp with label containing "STRING"
  7. SKIP tokens: any regexp whose tokenProduction kind is SKIPPED
--]
//! Lexer implementation. Generated by ${generated_by}. Do not edit.

use crate::error::{ParseError, ParseResult};
use crate::tokens::{Token, TokenType, LexicalState, TokenSource};

/// The lexer/tokenizer for ${settings.parserClassName}
pub struct Lexer {
    /// The input string being tokenized
    input: String,
    /// Current position in the input
    position: usize,
    /// Current lexical state
    state: LexicalState,
    /// All tokens generated so far
    tokens: Vec<Token>,
    /// Current line number (1-indexed)
    current_line: usize,
    /// Current column number (1-indexed)
    current_column: usize,
    /// Line start offsets for quick line/column lookup
    line_starts: Vec<usize>,
}

impl Lexer {
    /// Create a new lexer for the given input
    pub fn new(input: String) -> Self {
        let mut line_starts = vec![0];
        for (i, ch) in input.char_indices() {
            if ch == '\n' {
                line_starts.push(i + 1);
            }
        }

        Lexer {
            input,
            position: 0,
            state: LexicalState::${lexerData.lexicalStates[0].name},
            tokens: Vec::new(),
            current_line: 1,
            current_column: 1,
            line_starts,
        }
    }

    /// Get the next token from the input
    pub fn next_token(&mut self) -> ParseResult<Token> {
        // Skip whitespace and comments based on lexical state
        self.skip_ignored()?;

        if self.position >= self.input.len() {
            // Return EOF token
            return Ok(Token::new(
                TokenType::EOF,
                String::new(),
                self.position,
                self.position,
            ));
        }

        let start_pos = self.position;
        let start_line = self.current_line;
        let start_column = self.current_column;

        // Try to match each token type in order
        if let Some(token) = self.try_match_token(start_pos)? {
            return Ok(token);
        }

        // If no token matched, it's an error
        Err(ParseError::at_location(
            format!("Unexpected character: '{}'", self.current_char()),
            start_line,
            start_column,
        ))
    }

    /// Try to match a token at the current position
    fn try_match_token(&mut self, start_pos: usize) -> ParseResult<Option<Token>> {
        let ch = self.current_char();

[#--
  =====================================================================
  Phase 1: Multi-character operator literals (length >= 2), longest first.
  This includes both RegexpStringLiteral tokens and RegexpChoice alternatives.
  We do multiple passes: length >= 4, length == 3, length == 2.
  Only include non-private, non-skipped, non-keyword string literals.
  =====================================================================
--]
[#-- Pass for length >= 4 --]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && (!regexp.tokenProduction?? || regexp.tokenProduction.kind?string != "SKIPPED")]
[#if regexp.class.simpleName == "RegexpStringLiteral" && !regexp.ignoreCase && regexp.literalString?length >= 4]
        if self.matches_string("${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif regexp.class.simpleName == "RegexpChoice"]
[#list regexp.choices as choice]
[#if choice.class.simpleName == "RegexpStringLiteral" && choice.literalString?length >= 4]
        if self.matches_string("${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif choice.class.simpleName == "RegexpSequence" && choice.units?size == 1 && choice.units[0].class.simpleName == "RegexpStringLiteral" && choice.units[0].literalString?length >= 4]
        if self.matches_string("${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[/#if]
[/#list]
[/#if]
[/#if]
[/#list]
[#-- Pass for length == 3 --]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && (!regexp.tokenProduction?? || regexp.tokenProduction.kind?string != "SKIPPED")]
[#if regexp.class.simpleName == "RegexpStringLiteral" && !regexp.ignoreCase && regexp.literalString?length == 3]
        if self.matches_string("${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif regexp.class.simpleName == "RegexpChoice"]
[#list regexp.choices as choice]
[#if choice.class.simpleName == "RegexpStringLiteral" && choice.literalString?length == 3]
        if self.matches_string("${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif choice.class.simpleName == "RegexpSequence" && choice.units?size == 1 && choice.units[0].class.simpleName == "RegexpStringLiteral" && choice.units[0].literalString?length == 3]
        if self.matches_string("${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[/#if]
[/#list]
[/#if]
[/#if]
[/#list]
[#-- Pass for length == 2 --]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && (!regexp.tokenProduction?? || regexp.tokenProduction.kind?string != "SKIPPED")]
[#if regexp.class.simpleName == "RegexpStringLiteral" && !regexp.ignoreCase && regexp.literalString?length == 2]
        if self.matches_string("${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif regexp.class.simpleName == "RegexpChoice"]
[#list regexp.choices as choice]
[#if choice.class.simpleName == "RegexpStringLiteral" && choice.literalString?length == 2]
        if self.matches_string("${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[#elseif choice.class.simpleName == "RegexpSequence" && choice.units?size == 1 && choice.units[0].class.simpleName == "RegexpStringLiteral" && choice.units[0].literalString?length == 2]
        if self.matches_string("${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}") {
            return Ok(Some(self.consume_literal(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, "${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}", start_pos)));
        }
[/#if]
[/#list]
[/#if]
[/#if]
[/#list]
[#--
  =====================================================================
  Phase 2: Single-character operator literals (match block).
  =====================================================================
--]
        match ch {
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && (!regexp.tokenProduction?? || regexp.tokenProduction.kind?string != "SKIPPED")]
[#if regexp.class.simpleName == "RegexpStringLiteral" && !regexp.ignoreCase && regexp.literalString?length == 1]
            '${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}' => {
                self.advance();
                return Ok(Some(Token::new(
                    TokenType::${regexp.label?replace("_TOKEN_", "Token")},
                    "${regexp.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}".to_string(),
                    start_pos,
                    self.position,
                )));
            }
[/#if]
[#if regexp.class.simpleName == "RegexpChoice"]
[#list regexp.choices as choice]
[#if choice.class.simpleName == "RegexpStringLiteral" && choice.literalString?length == 1]
            '${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}' => {
                self.advance();
                return Ok(Some(Token::new(
                    TokenType::${regexp.label?replace("_TOKEN_", "Token")},
                    "${choice.literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}".to_string(),
                    start_pos,
                    self.position,
                )));
            }
[#elseif choice.class.simpleName == "RegexpSequence" && choice.units?size == 1 && choice.units[0].class.simpleName == "RegexpStringLiteral" && choice.units[0].literalString?length == 1]
            '${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}' => {
                self.advance();
                return Ok(Some(Token::new(
                    TokenType::${regexp.label?replace("_TOKEN_", "Token")},
                    "${choice.units[0].literalString?replace("\\", "\\\\")?replace("\"", "\\\"")}".to_string(),
                    start_pos,
                    self.position,
                )));
            }
[/#if]
[/#list]
[/#if]
[/#if]
[/#list]
            _ => {}
        }

[#--
  =====================================================================
  Phase 3: String literal matching (e.g., 'hello world')
  Detect tokens whose label contains "STRING_LITERAL" or "STRING".
  =====================================================================
--]
[#var hasStringLiteral = false]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && regexp.literalString?? == false && (regexp.label == "STRING_LITERAL" || regexp.label == "STRING")]
[#set hasStringLiteral = true]
[/#if]
[/#list]
[#if hasStringLiteral]
        // String literal (single-quoted)
        if ch == '\'' {
            return self.match_string_literal(start_pos);
        }

[/#if]
[#--
  =====================================================================
  Phase 4: Numeric literal matching (INTEGER, DECIMAL, INTEGER_LITERAL, DECIMAL_LITERAL)
  =====================================================================
--]
[#var hasInteger = false]
[#var integerLabel = ""]
[#var hasDecimal = false]
[#var decimalLabel = ""]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && regexp.literalString?? == false]
[#if regexp.label == "INTEGER" || regexp.label == "INTEGER_LITERAL"]
[#set hasInteger = true]
[#set integerLabel = regexp.label]
[#elseif regexp.label == "DECIMAL" || regexp.label == "DECIMAL_LITERAL"]
[#set hasDecimal = true]
[#set decimalLabel = regexp.label]
[/#if]
[/#if]
[/#list]
[#if hasInteger || hasDecimal]
        // Numeric literals
        if ch.is_ascii_digit() {
            return self.match_number(start_pos);
        }

[/#if]
[#--
  =====================================================================
  Phase 5: Identifier and keyword matching
  If grammar has an IDENTIFIER token, generate identifier consumption
  with keyword lookup for case-insensitive string literals.
  =====================================================================
--]
[#var hasIdentifier = false]
[#var hasKeywords = false]
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && regexp.literalString?? == false && regexp.label == "IDENTIFIER"]
[#set hasIdentifier = true]
[/#if]
[#if !regexp.private && regexp.class.simpleName == "RegexpStringLiteral" && regexp.ignoreCase]
[#set hasKeywords = true]
[/#if]
[/#list]
[#if hasIdentifier]
        // Identifiers and keywords
        if ch.is_ascii_alphabetic() || ch == '_' {
            return self.match_identifier_or_keyword(start_pos);
        }

[#elseif hasKeywords]
        // Keywords (case-insensitive matching)
        if ch.is_ascii_alphabetic() || ch == '_' {
            return self.match_keyword(start_pos);
        }

[/#if]
        // No token matched
        Ok(None)
    }

[#--
  =====================================================================
  Helper: consume_literal - advance past a literal string and return token
  =====================================================================
--]
    /// Consume a literal string token
    fn consume_literal(&mut self, token_type: TokenType, literal: &str, start_pos: usize) -> Token {
        for _ in 0..literal.len() {
            self.advance();
        }
        Token::new(token_type, literal.to_string(), start_pos, self.position)
    }

[#--
  =====================================================================
  Helper: match_string_literal - consume single-quoted string literal
  =====================================================================
--]
[#if hasStringLiteral]
    /// Match a single-quoted string literal
    fn match_string_literal(&mut self, start_pos: usize) -> ParseResult<Option<Token>> {
        // Consume opening quote
        self.advance();
        while self.position < self.input.len() {
            let ch = self.current_char();
            if ch == '\'' {
                self.advance(); // consume closing quote
                let image = self.input[start_pos..self.position].to_string();
                return Ok(Some(Token::new(
                    TokenType::STRING_LITERAL,
                    image,
                    start_pos,
                    self.position,
                )));
            }
            self.advance();
        }
        // Unterminated string literal
        Err(ParseError::at_position(
            "Unterminated string literal".to_string(),
            start_pos,
        ))
    }

[/#if]
[#--
  =====================================================================
  Helper: match_number - consume integer or decimal literal
  =====================================================================
--]
[#if hasInteger || hasDecimal]
    /// Match a numeric literal (integer or decimal)
    fn match_number(&mut self, start_pos: usize) -> ParseResult<Option<Token>> {
        // Consume leading digits
        while self.position < self.input.len() && self.current_char().is_ascii_digit() {
            self.advance();
        }
[#if hasDecimal]
        // Check for decimal point followed by digits
        if self.position < self.input.len() && self.current_char() == '.' {
            if let Some(next_ch) = self.peek(1) {
                if next_ch.is_ascii_digit() {
                    self.advance(); // consume '.'
                    while self.position < self.input.len() && self.current_char().is_ascii_digit() {
                        self.advance();
                    }
                    let image = self.input[start_pos..self.position].to_string();
                    return Ok(Some(Token::new(
                        TokenType::${decimalLabel},
                        image,
                        start_pos,
                        self.position,
                    )));
                }
            }
        }
[/#if]
        let image = self.input[start_pos..self.position].to_string();
        return Ok(Some(Token::new(
[#if hasInteger]
            TokenType::${integerLabel},
[#else]
            TokenType::${decimalLabel},
[/#if]
            image,
            start_pos,
            self.position,
        )));
    }

[/#if]
[#--
  =====================================================================
  Helper: match_identifier_or_keyword - consume identifier, check keywords
  =====================================================================
--]
[#if hasIdentifier]
    /// Match an identifier or keyword
    fn match_identifier_or_keyword(&mut self, start_pos: usize) -> ParseResult<Option<Token>> {
        // Consume identifier characters
        while self.position < self.input.len() {
            let ch = self.current_char();
            if ch.is_ascii_alphanumeric() || ch == '_' {
                self.advance();
            } else {
                break;
            }
        }
        let image = self.input[start_pos..self.position].to_string();
        let upper = image.to_ascii_uppercase();

        // Check against keywords (case-insensitive)
        let token_type = match upper.as_str() {
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && regexp.class.simpleName == "RegexpStringLiteral" && regexp.ignoreCase]
            "${regexp.literalString?upper_case}" => TokenType::${regexp.label?replace("_TOKEN_", "Token")},
[/#if]
[/#list]
            _ => TokenType::IDENTIFIER,
        };

        Ok(Some(Token::new(token_type, image, start_pos, self.position)))
    }

[#elseif hasKeywords]
    /// Match a keyword
    fn match_keyword(&mut self, start_pos: usize) -> ParseResult<Option<Token>> {
        // Consume alphabetic/underscore characters
        while self.position < self.input.len() {
            let ch = self.current_char();
            if ch.is_ascii_alphanumeric() || ch == '_' {
                self.advance();
            } else {
                break;
            }
        }
        let image = self.input[start_pos..self.position].to_string();
        let upper = image.to_ascii_uppercase();

        // Check against keywords (case-insensitive)
        match upper.as_str() {
[#list lexerData.regularExpressions as regexp]
[#if !regexp.private && regexp.class.simpleName == "RegexpStringLiteral" && regexp.ignoreCase]
            "${regexp.literalString?upper_case}" => {
                Ok(Some(Token::new(TokenType::${regexp.label?replace("_TOKEN_", "Token")}, image, start_pos, self.position)))
            }
[/#if]
[/#list]
            _ => Ok(None),
        }
    }

[/#if]
    /// Skip whitespace and ignored tokens
    fn skip_ignored(&mut self) -> ParseResult<()> {
        while self.position < self.input.len() {
            let ch = self.current_char();

            // Skip whitespace
            if ch.is_whitespace() {
                self.advance();
                continue;
            }

            break;
        }
        Ok(())
    }

    /// Get the current character without consuming it
    fn current_char(&self) -> char {
        self.input[self.position..].chars().next().unwrap_or('\0')
    }

    /// Advance to the next character
    fn advance(&mut self) {
        if self.position < self.input.len() {
            let ch = self.current_char();
            self.position += ch.len_utf8();

            if ch == '\n' {
                self.current_line += 1;
                self.current_column = 1;
            } else {
                self.current_column += 1;
            }
        }
    }

    /// Peek ahead n characters without consuming
    fn peek(&self, n: usize) -> Option<char> {
        self.input[self.position..].chars().nth(n)
    }

    /// Check if current position matches a string
    fn matches_string(&self, s: &str) -> bool {
        self.input[self.position..].starts_with(s)
    }
}

impl TokenSource for Lexer {
    fn get_line_from_offset(&self, offset: usize) -> usize {
        // Binary search for the line containing this offset
        match self.line_starts.binary_search(&offset) {
            Ok(line) => line + 1,
            Err(line) => line,
        }
    }

    fn get_column_from_offset(&self, offset: usize) -> usize {
        let line_num = self.get_line_from_offset(offset);
        if line_num == 0 || line_num > self.line_starts.len() {
            return 1;
        }

        let line_start = self.line_starts[line_num - 1];
        offset.saturating_sub(line_start) + 1
    }
}
