//! ArithmeticParser - Generated by CongoCC Parser Generator
//!
//! This parser was automatically generated from: SimpleArithmetic.ccc
//! Do not edit this file directly. Regenerate from the grammar instead.
//!
//! # Features
//!
//! - **Arena-based allocation**: All AST nodes and tokens are stored in a central arena
//! - **Type-safe indices**: `NodeId` and `TokenId` provide safe references without lifetimes
//! - **Result-based errors**: All parsing operations return `Result<T, ParseError>`
//! - **Location tracking**: Errors include line/column information for better diagnostics
//!
//! # Example
//!
//! ```ignore
//! use arithmetic::*;
//!
//! fn main() -> Result<(), ParseError> {
//!     let input = "your input here".to_string();
//!     let mut parser = Parser::new(input)?;
//!     // parse() returns the root NodeId of the AST
//!     let root = parser.parse()?;
//!     // Access AST through the arena, with original input for pretty printing
//!     println!("{}", parser.arena().pretty_print(root, 0, parser.input()));
//!     Ok(())
//! }
//! ```

#![deny(unsafe_code)]
#![warn(missing_docs)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]

mod error;
mod tokens;
mod arena;
mod lexer;
mod parser;
mod visitor;

// Re-export public API
pub use error::{ParseError, ParseResult};
pub use tokens::{Token, TokenType, LexicalState, TokenSource};
pub use arena::{Arena, NodeId, TokenId, AstNode};
pub use lexer::Lexer;
pub use parser::Parser;
pub use visitor::VisitControl;

// Re-export AST node types and operator enums
pub use arena::ExpressionNode;
pub use arena::AdditiveExpressionNode;
pub use arena::MultiplicativeExpressionNode;
pub use arena::PrimaryNode;
pub use arena::AdditiveOp;
pub use arena::MultiplicativeOp;
